name: PyPI publish on release
on:
  release:
    types: [published]
defaults:
  run:
    shell:
      bash
jobs:
  build-package:
    runs-on: ubuntu-20.04
    if: github.repository == "coqui-ai/stt-model-manager"
    steps:
      - uses: actions/checkout@v2
      - name: Verify tag matches version
        run: |
          set -ex
          version=$(cat VERSION)
          tag="${GITHUB_REF/refs\/tags\/}"
          if [[ "v$version" != "$tag" ]]; then
            exit 1
          fi
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install -U pip setuptools wheel twine
      - run: |
          make package
      - run: |
          ls -lh dist/
      - name: Setup PyPI config
        run: |
          cat << EOF > ~/.pypirc
          [pypi]
          username=__token__
          password=${{ secrets.PYPI_TOKEN }}
          EOF
      - run: |
          twine upload --repository pypi dist/*
